FROM node:22-alpine AS base
WORKDIR /app

# Install production dependencies
FROM base AS prod-deps
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Install all dependencies (including dev) for building
FROM base AS build-deps
COPY package.json package-lock.json ./
RUN npm ci

# Build the Astro app
FROM build-deps AS build
COPY . .
RUN npm run build

# Final runtime image
FROM base AS runtime
# Set environment variables for Astro Node adapter
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321

# Copy production dependencies and built files
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

# Expose the default Astro port
EXPOSE 4321

# Run the Node.js standalone server generated by Astro
CMD ["node", "./dist/server/entry.mjs"]
